version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /api/.*
  script: api.app

- url: /(.*)
  static_files: static/\1
  upload: static/.*